-- 0009_verify_ban_data_layer.sql
--
-- NOT a migration. Run in the Supabase SQL editor AFTER applying 0009, to
-- prove the restrictive write gate behaves as intended through real RLS.
-- 0009's own pre-commit guard tests the rule function and the policy metadata;
-- this tests the thing neither of those can: actual policy evaluation as the
-- `authenticated` role.
--
-- Safe against production: everything runs inside a transaction ending in
-- ROLLBACK. It borrows an existing non-admin profile, cycles it through all
-- four statuses, and discards every change. It does not insert into auth.users
-- (whose required columns vary by GoTrue version).
--
-- TWO THINGS THAT MAKE THIS TRICKIER THAN IT LOOKS, both learned the hard way:
--
--   1. RLS is not enforced for the table owner. The SQL editor runs as
--      `postgres`, which owns these tables, so the write test MUST switch to
--      `set local role authenticated` or it silently passes everything.
--
--   2. auth.role() reads the JWT *claim*, not the Postgres role. The
--      profiles_lock_account_status trigger from 0007 checks
--      `auth.role() <> 'service_role'`, so flipping account_status requires
--      setting request.jwt.claims.role to 'service_role' — `set role
--      service_role` does nothing for it, and the trigger will quietly revert
--      the status while every test appears to run fine. The assertion after
--      each flip exists specifically to catch that.
--
-- Bookkeeping (the temp table) is written only while the role is back to the
-- session default, since `authenticated` has no rights on it.
--
-- Expected output:
--   result set 1 — 12 rows, every `result` reading PASS
--   result set 2 — failures = 0
--   result set 3 — informational only (Step 3 backfill worklist)

begin;

create temp table rls_check_results (
  seq int generated by default as identity,
  scenario text,
  operation text,
  expected text,
  actual text,
  result text
) on commit drop;

do $$
declare
  v_user   uuid;
  v_list   uuid;
  v_status text;
  v_until  timestamptz;
  v_expect text;
  v_actual text;
  v_seen   text;
  v_reads  int;
  v_label  text;
  -- status | suspended_until | expected write outcome
  v_cases  text[][] := array[
    ['active',    'none',   'allowed'],
    ['frozen',    'none',   'allowed'],
    ['suspended', 'none',   'denied' ],  -- open-ended: never auto-expires
    ['suspended', 'past',   'allowed'],  -- time-boxed and already elapsed
    ['suspended', 'future', 'denied' ],
    ['banned',    'none',   'denied' ]
  ];
begin
  select id into v_user
  from profiles
  where is_admin = false
  order by created_at
  limit 1;

  if v_user is null then
    raise exception 'No non-admin profile exists to test against — create a normal user first.';
  end if;

  -- Seeded as the owner, so RLS does not apply to this insert.
  insert into lists (id, user_id, name, kind)
  values (gen_random_uuid(), v_user, 'rls-check-seed', 'company')
  returning id into v_list;

  for i in 1 .. array_length(v_cases, 1) loop
    v_status := v_cases[i][1];
    v_expect := v_cases[i][3];
    v_until  := case v_cases[i][2]
                  when 'past'   then now() - interval '1 day'
                  when 'future' then now() + interval '1 day'
                  else null
                end;
    v_label  := v_status || ' / until=' || v_cases[i][2];

    -- ── flip the status ──────────────────────────────────────────────
    -- role=service_role in the CLAIMS is what satisfies the 0007 trigger.
    perform set_config('request.jwt.claims',
      json_build_object('sub', v_user, 'role', 'service_role')::text, true);

    update profiles
    set account_status = v_status, suspended_until = v_until
    where id = v_user;

    -- Assert it actually stuck. If the trigger reverted it, every case below
    -- would silently test the wrong status and report nonsense.
    select account_status into v_seen from profiles where id = v_user;
    if v_seen is distinct from v_status then
      raise exception 'could not set status to % (got %) — the profiles trigger reverted it', v_status, v_seen;
    end if;

    -- ── test as the user ─────────────────────────────────────────────
    perform set_config('request.jwt.claims',
      json_build_object('sub', v_user, 'role', 'authenticated')::text, true);
    set local role authenticated;

    -- WRITE. RLS denies an UPDATE by matching zero rows rather than raising,
    -- so FOUND is the signal. A genuine privilege error is reported distinctly
    -- so a missing table GRANT is never mistaken for an RLS denial.
    begin
      update lists set name = 'rls-check-' || v_status where id = v_list;
      v_actual := case when found then 'allowed' else 'denied' end;
    exception when insufficient_privilege then
      v_actual := 'GRANT-ERROR';
    end;

    -- READ. Must stay allowed for every status, banned included — the lockout
    -- screen and the user's own support thread both depend on it.
    begin
      select count(*) into v_reads from lists where id = v_list;
    exception when insufficient_privilege then
      v_reads := -1;
    end;

    -- ── record (back as the session role; authenticated cannot write here) ──
    reset role;

    insert into rls_check_results (scenario, operation, expected, actual, result)
    values (v_label, 'update own list', v_expect, v_actual,
            case when v_actual = v_expect then 'PASS' else 'FAIL' end);

    insert into rls_check_results (scenario, operation, expected, actual, result)
    values (v_label, 'select own list', 'allowed',
            case v_reads when 1 then 'allowed' when -1 then 'GRANT-ERROR' else 'denied' end,
            case when v_reads = 1 then 'PASS' else 'FAIL' end);
  end loop;

  reset role;
  perform set_config('request.jwt.claims', '', true);
end $$;

reset role;

select seq, scenario, operation, expected, actual, result
from rls_check_results
order by seq;

select count(*) filter (where result = 'FAIL') as failures,
       count(*) filter (where result = 'PASS') as passes
from rls_check_results;

-- Informational, not pass/fail. Users still banned at the GoTrue layer, i.e.
-- who cannot sign in to appeal yet. Clearing these is Step 3's job (it has to
-- happen after setUserAccountStatus stops re-applying the ban), so rows here
-- are expected right now — this is just the worklist.
select u.id, u.email, u.banned_until, p.account_status
from auth.users u
join profiles p on p.id = u.id
where u.banned_until is not null;

rollback;
