-- 0008_support_tickets.sql
-- Support ticketing. This is the "Phase 2 user ticket-raising flow" that
-- 0007_account_status.sql was designed to be forward-compatible with.
--
-- Purely additive: four new tables, one new nullable profiles column, one
-- private storage bucket. No existing table, policy, or row is modified, so
-- applying this on its own changes nothing about how the product behaves
-- today. (The one exception is prevent_account_status_self_change, which is
-- REPLACED rather than altered — see the note above it; the replacement is a
-- strict superset of the 0007 version.)
--
-- Scope decision: tickets are for authenticated users only. There is no
-- public/anonymous submission path, by design — which is why there is no
-- email-verification, captcha, or IP-tracking machinery here. Every requester
-- is a real profiles row.
--
-- Writes: every table below has a SELECT policy and *no* insert/update/delete
-- policy. RLS default-denies what it has no policy for, so the backend service
-- role (which bypasses RLS) is the only writer. That is deliberate — ticket
-- caps, rate limits, status-transition validation, and the internal-note
-- boundary are all enforced in one place instead of being spread across
-- client-side calls.

-- ALL OR NOTHING. Wrapped explicitly because the Supabase SQL editor otherwise
-- commits statement by statement, and the storage section at the bottom is the
-- one part with a realistic chance of failing on some projects (policy
-- creation on storage.objects needs ownership of that table). Without the
-- transaction, that failure would leave the four tables committed and the
-- bucket missing — and re-running would then fail on `create table` instead of
-- picking up where it stopped.

begin;

-- ── profiles: support mute ──────────────────────────────────────────────
-- Escape valve for an abusive requester (realistically: a banned user
-- flooding the queue with appeals). Null = not muted, which is every existing
-- and future row until an admin sets it.

alter table profiles
  add column support_muted_until timestamptz;

-- REPLACES the 0007 function, adding support_muted_until to the locked set.
-- Without this the lock is trivially bypassed: profiles_update_own lets a user
-- update their own row, so a muted user could simply clear their own mute.
-- Everything else about the function is unchanged from 0007 — same silent
-- revert-to-old-values behavior, same service_role carve-out.
create or replace function prevent_account_status_self_change()
returns trigger
language plpgsql
as $$
begin
  if auth.role() <> 'service_role' and (
       new.account_status   is distinct from old.account_status
    or new.status_reason    is distinct from old.status_reason
    or new.suspended_until  is distinct from old.suspended_until
    or new.status_updated_at is distinct from old.status_updated_at
    or new.status_updated_by is distinct from old.status_updated_by
    or new.support_muted_until is distinct from old.support_muted_until
  ) then
    new.account_status      := old.account_status;
    new.status_reason       := old.status_reason;
    new.suspended_until     := old.suspended_until;
    new.status_updated_at   := old.status_updated_at;
    new.status_updated_by   := old.status_updated_by;
    new.support_muted_until := old.support_muted_until;
  end if;
  return new;
end;
$$;

-- ── support_tickets ─────────────────────────────────────────────────────

create table support_tickets (
  id uuid primary key default gen_random_uuid(),

  -- Human-facing reference ("#1042"). Support conversations need a short
  -- number a person can read out; the uuid is the real key everywhere else.
  ticket_number bigint generated by default as identity unique,

  user_id uuid not null references profiles(id) on delete cascade,

  category text not null check (category in (
    'billing', 'credits', 'data_quality', 'account_access', 'bug', 'feature_request', 'other'
  )),
  subject text not null check (char_length(subject) between 1 and 200),

  status text not null default 'open' check (status in (
    'open', 'in_progress', 'waiting_on_user', 'resolved', 'closed'
  )),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  assigned_to uuid references profiles(id) on delete set null,

  -- Where the ticket was raised from. 'lockout' means the requester was on the
  -- suspended/banned screen — i.e. almost certainly an appeal, and worth
  -- surfacing distinctly in the admin queue.
  source text not null default 'app' check (source in ('app', 'lockout', 'admin')),

  -- Snapshot, not a live join: what the account looked like when the ticket
  -- was filed. An admin reading a three-week-old ticket needs to know the user
  -- was suspended *then*, regardless of what they are now.
  account_status_at_submit text not null check (account_status_at_submit in (
    'active', 'frozen', 'suspended', 'banned'
  )),

  -- Optional pointer to the thing the ticket is about, so a "this reveal
  -- returned a dead email" report carries its run id instead of the admin
  -- having to reconstruct it. Cheap now, painful to retrofit later.
  context_ref_type text check (context_ref_type in ('run', 'list', 'payment')),
  context_ref_id uuid,

  -- SLA / triage timestamps. first_response_at is set by the first
  -- *non-internal* admin message only — an internal note is not a response.
  first_response_at timestamptz,
  resolved_at timestamptz,
  closed_at timestamptz,

  -- Denormalized thread state so the queue list never has to join or
  -- aggregate support_messages to sort by activity or show an unread dot.
  last_message_at timestamptz not null default now(),
  last_message_role text not null default 'user' check (last_message_role in ('user', 'admin', 'system')),
  user_read_at timestamptz,
  admin_read_at timestamptz,

  -- Hash of (category, subject, body) at creation. Backs the unique index
  -- below, which is what actually makes double-submit safe.
  dedupe_hash text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- A ticket is resolved/closed or it isn't; keep the timestamps honest so
  -- SLA reporting can trust them.
  constraint support_tickets_resolved_at_ck check (
    (status = 'resolved' and resolved_at is not null)
    or (status = 'closed')
    or (status not in ('resolved', 'closed') and resolved_at is null)
  ),
  constraint support_tickets_closed_at_ck check (
    (status = 'closed') = (closed_at is not null)
  ),
  constraint support_tickets_context_ref_ck check (
    (context_ref_type is null) = (context_ref_id is null)
  )
);

create trigger support_tickets_set_updated_at
  before update on support_tickets
  for each row execute function set_updated_at();

-- Race-proof double-submit protection. A partial unique index rather than a
-- backend "did we just see this?" lookup, because two concurrent identical
-- submits would both pass a lookup. The backend catches the 23505 and returns
-- the existing ticket instead of erroring. Scoped to non-closed tickets so a
-- user can legitimately re-report the same problem months later.
create unique index support_tickets_dedupe_idx
  on support_tickets(user_id, dedupe_hash)
  where dedupe_hash is not null and status <> 'closed';

create index support_tickets_user_id_idx on support_tickets(user_id, created_at desc);
create index support_tickets_status_idx on support_tickets(status, last_message_at desc);
create index support_tickets_assigned_to_idx on support_tickets(assigned_to, status)
  where assigned_to is not null;

-- The admin queue's default view is "everything not closed", which stays small
-- relative to total volume — a partial index keeps that query flat as the
-- closed archive grows.
create index support_tickets_open_idx on support_tickets(last_message_at desc)
  where status <> 'closed';

alter table support_tickets enable row level security;

create policy support_tickets_select_own on support_tickets
  for select using (user_id = auth.uid() or is_admin());

-- ── support_messages ────────────────────────────────────────────────────
-- The thread. Append-only by policy (no update/delete policy exists), so a
-- reply can't be silently rewritten after the fact.
--
-- Internal admin notes live in this same table behind is_internal. That is the
-- single most dangerous column in this migration: leaking one to a customer is
-- unrecoverable. It is therefore filtered *here*, in RLS, in addition to the
-- backend query — belt and braces, because the failure mode is not survivable.

create table support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references support_tickets(id) on delete cascade,
  author_id uuid references profiles(id) on delete set null,
  author_role text not null check (author_role in ('user', 'admin', 'system')),
  body text not null check (char_length(body) between 1 and 5000),
  is_internal boolean not null default false,
  created_at timestamptz not null default now(),

  -- Only an admin can author an internal note. Makes "user message
  -- accidentally flagged internal" (which would hide it from the admin's
  -- customer-facing view) unrepresentable.
  constraint support_messages_internal_is_admin_ck check (not is_internal or author_role = 'admin')
);

create index support_messages_ticket_idx on support_messages(ticket_id, created_at);

alter table support_messages enable row level security;

create policy support_messages_select_own on support_messages
  for select using (
    is_admin()
    or (
      is_internal = false
      and exists (
        select 1 from support_tickets t
        where t.id = support_messages.ticket_id and t.user_id = auth.uid()
      )
    )
  );

-- ── support_events ──────────────────────────────────────────────────────
-- Admin-side audit trail: who changed status, who assigned what, when it was
-- auto-closed. Same append-only, admin-only shape as moderation_actions in
-- 0007 (select + no write policy). Not user-visible; the customer sees the
-- message thread, not the operational timeline.

create table support_events (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references support_tickets(id) on delete cascade,
  actor_id uuid references profiles(id) on delete set null,
  actor_role text not null check (actor_role in ('user', 'admin', 'system')),
  event_type text not null check (event_type in (
    'created', 'status_changed', 'priority_changed', 'assigned', 'unassigned',
    'reopened', 'auto_closed', 'capped', 'muted'
  )),
  from_value text,
  to_value text,
  note text,
  created_at timestamptz not null default now()
);

create index support_events_ticket_idx on support_events(ticket_id, created_at);

alter table support_events enable row level security;

create policy support_events_admin_select on support_events
  for select using (is_admin());

-- ── support_attachments ─────────────────────────────────────────────────
-- Metadata only; bytes live in the private storage bucket created below.
--
-- is_internal is denormalized from the parent message on purpose. A join is
-- one forgotten clause away from serving an internal screenshot to the
-- customer, and the same reasoning as support_messages applies: make the
-- dangerous case impossible to reach by accident, not merely unlikely.

create table support_attachments (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references support_tickets(id) on delete cascade,
  message_id uuid references support_messages(id) on delete cascade,
  uploaded_by uuid references profiles(id) on delete set null,
  storage_path text not null unique,
  filename text not null check (char_length(filename) between 1 and 255),
  mime text not null check (mime in ('image/png', 'image/jpeg', 'image/webp', 'application/pdf')),
  size_bytes integer not null check (size_bytes > 0 and size_bytes <= 5242880),
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

create index support_attachments_ticket_idx on support_attachments(ticket_id);
create index support_attachments_message_idx on support_attachments(message_id);

alter table support_attachments enable row level security;

create policy support_attachments_select_own on support_attachments
  for select using (
    is_admin()
    or (
      is_internal = false
      and exists (
        select 1 from support_tickets t
        where t.id = support_attachments.ticket_id and t.user_id = auth.uid()
      )
    )
  );

-- ── storage bucket ──────────────────────────────────────────────────────
-- Private bucket with Storage-enforced size and MIME limits, so a malformed
-- upload is rejected before it ever reaches our code.
--
-- image/svg+xml is deliberately absent from the allowlist. An SVG is a script
-- container; served from our own origin it is stored XSS. PNG/JPEG/WEBP cover
-- every real screenshot, and PDF covers invoices.
--
-- A client can still lie about Content-Type (Storage trusts the declared
-- header, it does not sniff bytes). That is contained rather than prevented:
-- the bucket is private, downloads go through short-lived signed URLs, and the
-- response carries the *stored* content type — so an HTML payload uploaded as
-- image/png is served as image/png and never executes.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'support-attachments',
  'support-attachments',
  false,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'application/pdf']
)
on conflict (id) do nothing;

-- Uploads are scoped to a per-user folder: support-attachments/<auth.uid()>/…
-- Note this insert policy has no account-status condition — a suspended or
-- banned user must be able to attach a screenshot to their appeal. Volume is
-- bounded by the per-message attachment cap and the open-ticket cap, both
-- enforced by the backend.
create policy support_attachments_object_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'support-attachments'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy support_attachments_object_select on storage.objects
  for select to authenticated
  using (
    bucket_id = 'support-attachments'
    and ((storage.foldername(name))[1] = auth.uid()::text or is_admin())
  );

-- No update or delete policy, intentionally. Removing a file from the composer
-- before sending just drops it client-side; the object is left orphaned and
-- reaped by the backend's sweep. Letting clients delete would otherwise leave
-- support_attachments rows pointing at objects that no longer exist, which is
-- a worse problem than a few stray bytes.

commit;
